BEGIN;

CREATE TABLE IF NOT EXISTS public.report_progress_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES public.reports(id) ON DELETE RESTRICT,
  note TEXT NOT NULL CHECK (length(trim(note)) BETWEEN 1 AND 5000),
  created_by BIGINT NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  request_id UUID NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS report_progress_history_idx
  ON public.report_progress_notes(report_id, id DESC);

ALTER TABLE public.report_progress_notes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.report_progress_notes
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.report_progress_notes TO authenticated, service_role;
REVOKE ALL ON SEQUENCE public.report_progress_notes_id_seq
  FROM PUBLIC, anon, authenticated, service_role;

DROP POLICY IF EXISTS report_progress_read ON public.report_progress_notes;
CREATE POLICY report_progress_read
ON public.report_progress_notes FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users AS u
    WHERE u.auth_user_id = (SELECT auth.uid()) AND u.status = 'aktif'
      AND (
        u.role IN ('petugas', 'admin')
        OR (
          u.role = 'pengguna' AND EXISTS (
            SELECT 1 FROM public.reports AS r
            WHERE r.id = report_progress_notes.report_id AND r.user_id = u.id
          )
        )
      )
  )
);

CREATE OR REPLACE FUNCTION public.add_report_progress_note(
  p_report_id BIGINT, p_note TEXT, p_request_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_staff_id BIGINT;
  v_status TEXT;
  v_entry public.report_progress_notes%ROWTYPE;
BEGIN
  SELECT u.id INTO v_staff_id FROM public.users AS u
  WHERE u.auth_user_id = auth.uid() AND u.role = 'petugas' AND u.status = 'aktif'
  FOR SHARE;
  IF v_staff_id IS NULL THEN
    RAISE EXCEPTION 'Hanya petugas aktif yang dapat menambahkan perkembangan laporan.';
  END IF;
  IF p_note IS NULL OR length(trim(p_note)) NOT BETWEEN 1 AND 5000 THEN
    RAISE EXCEPTION 'Catatan perkembangan wajib diisi, maksimal 5000 karakter.';
  END IF;
  IF p_request_id IS NULL THEN
    RAISE EXCEPTION 'ID penyimpanan wajib diisi.';
  END IF;

  -- Kunci yang sama dengan pembaruan status: penutupan dan pencatatan berurutan.
  SELECT r.status INTO v_status FROM public.reports AS r
  WHERE r.id = p_report_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Laporan tidak ditemukan.'; END IF;

  SELECT n.* INTO v_entry FROM public.report_progress_notes AS n
  WHERE n.request_id = p_request_id;
  IF FOUND THEN
    IF v_entry.report_id <> p_report_id OR v_entry.created_by <> v_staff_id
       OR v_entry.note <> trim(p_note) THEN
      RAISE EXCEPTION 'ID penyimpanan sudah digunakan untuk catatan lain.';
    END IF;
  ELSE
    IF v_status <> 'diproses' THEN
      RAISE EXCEPTION 'Catatan perkembangan hanya dapat ditambahkan pada laporan berstatus Diproses.';
    END IF;
    INSERT INTO public.report_progress_notes(report_id, note, created_by, request_id)
    VALUES (p_report_id, trim(p_note), v_staff_id, p_request_id)
    RETURNING * INTO v_entry;
  END IF;

  -- Tidak mengubah status, waktu perubahan status, maupun catatan resolusi.
  RETURN jsonb_build_object(
    'id', v_entry.id::TEXT, 'note', v_entry.note, 'created_at', v_entry.created_at
  );
END;
$$;

REVOKE ALL ON FUNCTION public.add_report_progress_note(BIGINT, TEXT, UUID)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.add_report_progress_note(BIGINT, TEXT, UUID)
  TO authenticated;

NOTIFY pgrst, 'reload schema';
COMMIT;
