BEGIN;

CREATE TABLE public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id BIGINT NOT NULL
    REFERENCES public.users(id) ON DELETE RESTRICT,

  facility_id BIGINT NOT NULL
    REFERENCES public.facilities(id) ON DELETE RESTRICT,

  category VARCHAR(30) NOT NULL
    CHECK (
      category IN (
        'peralatan',
        'listrik',
        'kebersihan',
        'bangunan',
        'lainnya'
      )
    ),

  description TEXT NOT NULL
    CHECK (length(trim(description)) > 0),

  photo_path TEXT NOT NULL UNIQUE
    CHECK (length(trim(photo_path)) > 0),

  status VARCHAR(20) NOT NULL DEFAULT 'baru'
    CHECK (
      status IN ('baru', 'diproses', 'selesai', 'ditolak')
    ),

  officer_note TEXT NOT NULL DEFAULT '',

  processed_by BIGINT
    REFERENCES public.users(id) ON DELETE RESTRICT,

  processed_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT reports_closed_note_required CHECK (
    status NOT IN ('selesai', 'ditolak')
    OR length(trim(officer_note)) > 0
  ),

  CONSTRAINT reports_processing_info_required CHECK (
    (
      status = 'baru'
      AND processed_by IS NULL
      AND processed_at IS NULL
    )
    OR
    (
      status <> 'baru'
      AND processed_by IS NOT NULL
      AND processed_at IS NOT NULL
    )
  )
);

CREATE INDEX reports_user_created_idx
  ON public.reports(user_id, created_at DESC);

CREATE INDEX reports_facility_idx
  ON public.reports(facility_id);

CREATE INDEX reports_status_created_idx
  ON public.reports(status, created_at DESC);

CREATE INDEX reports_processed_by_idx
  ON public.reports(processed_by);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.reports FROM anon, authenticated;
GRANT SELECT ON TABLE public.reports TO authenticated;

REVOKE ALL ON SEQUENCE public.reports_id_seq
  FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON TABLE public.reports
  TO service_role;

GRANT USAGE, SELECT ON SEQUENCE public.reports_id_seq
  TO service_role;

CREATE POLICY reports_read_by_owner_or_staff
ON public.reports
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.users AS profile
    WHERE profile.auth_user_id = (SELECT auth.uid())
      AND profile.status = 'aktif'
      AND (
        (
          profile.role = 'pengguna'
          AND profile.id = reports.user_id
        )
        OR profile.role IN ('petugas', 'admin')
      )
  )
);

COMMIT;