BEGIN;

-- Memastikan pasangan laporan dan fasilitas dapat menjadi acuan.
CREATE UNIQUE INDEX reports_id_facility_unique
ON public.reports (id, facility_id);

CREATE TABLE public.facility_maintenance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  facility_id BIGINT NOT NULL
    REFERENCES public.facilities(id) ON DELETE RESTRICT,

  report_id BIGINT NOT NULL,

  reason TEXT NOT NULL
    CHECK (length(trim(reason)) BETWEEN 1 AND 5000),

  started_by BIGINT NOT NULL
    REFERENCES public.users(id) ON DELETE RESTRICT,

  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  completed_by BIGINT
    REFERENCES public.users(id) ON DELETE RESTRICT,

  completed_at TIMESTAMPTZ,

  completion_note TEXT,

  CONSTRAINT maintenance_report_facility_match
    FOREIGN KEY (report_id, facility_id)
    REFERENCES public.reports(id, facility_id)
    ON DELETE RESTRICT,

  CONSTRAINT maintenance_completion_valid CHECK (
    (
      completed_at IS NULL
      AND completed_by IS NULL
      AND completion_note IS NULL
    )
    OR
    (
      completed_at IS NOT NULL
      AND completed_by IS NOT NULL
      AND completion_note IS NOT NULL
      AND length(trim(completion_note)) BETWEEN 1 AND 5000
      AND completed_at >= started_at
    )
  )
);

-- Satu fasilitas memiliki paling banyak satu kegiatan perbaikan terbuka.
CREATE UNIQUE INDEX maintenance_one_open_per_facility
ON public.facility_maintenance (facility_id)
WHERE completed_at IS NULL;

CREATE INDEX maintenance_facility_history_idx
ON public.facility_maintenance (facility_id, started_at DESC);

CREATE INDEX maintenance_report_idx
ON public.facility_maintenance (report_id);

CREATE INDEX maintenance_started_by_idx
ON public.facility_maintenance (started_by);

CREATE INDEX maintenance_completed_by_idx
ON public.facility_maintenance (completed_by);

ALTER TABLE public.facility_maintenance
ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.facility_maintenance
FROM PUBLIC, anon, authenticated, service_role;

GRANT SELECT ON TABLE public.facility_maintenance
TO authenticated;

GRANT SELECT, INSERT, UPDATE ON TABLE public.facility_maintenance
TO service_role;

REVOKE ALL ON SEQUENCE public.facility_maintenance_id_seq
FROM PUBLIC, anon, authenticated, service_role;

GRANT USAGE, SELECT ON SEQUENCE public.facility_maintenance_id_seq
TO service_role;

CREATE POLICY maintenance_read_by_staff
ON public.facility_maintenance
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.users AS profile
    WHERE profile.auth_user_id = (SELECT auth.uid())
      AND profile.status = 'aktif'
      AND profile.role IN ('petugas', 'admin')
  )
);

COMMIT;