-- 1. Tabel Facilities (Placeholder kompatibel dengan modul Eve)
CREATE TABLE IF NOT EXISTS public.facilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(100),
  location VARCHAR(255),
  capacity INTEGER,
  description TEXT,
  status VARCHAR(50) DEFAULT 'aktif' CHECK (status IN ('aktif', 'nonaktif', 'dalam_perbaikan')),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on facilities
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;

-- Facilities policy: siapapun bisa membaca data fasilitas aktif/publik
DROP POLICY IF EXISTS "Public can view facilities" ON public.facilities;
CREATE POLICY "Public can view facilities" ON public.facilities
  FOR SELECT USING (true);

-- 1b. Tabel Users (PLACEHOLDER — Chapter 2)
-- Tabel `users` seharusnya dibuat oleh modul Alyssa (Akun & Role).
-- Jika belum ada saat migration ini dijalankan, buat versi minimal yang
-- memuat kolom yang dibutuhkan modul reservasi (id, auth_user_id, role,
-- serta name/email/status/created_at agar join & alur login tetap jalan).
-- MODUL ALYSSA AKAN MELENGKAPI kolom lainnya (nim_nip, jenis_pengguna,
-- verifikasi admin, dll). Jangan menghapus kolom dasar ini.
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id UUID UNIQUE,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  role VARCHAR(20) NOT NULL DEFAULT 'pengguna'
    CHECK (role IN ('pengguna', 'petugas', 'admin')),
  status VARCHAR(20) NOT NULL DEFAULT 'aktif'
    CHECK (status IN ('menunggu', 'aktif', 'ditolak')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Tabel Reservations (Modul Bagas)
CREATE TABLE IF NOT EXISTS public.reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  facility_id BIGINT NOT NULL REFERENCES public.facilities(id) ON DELETE CASCADE,
  reservation_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  purpose TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'menunggu' 
    CHECK (status IN ('menunggu', 'disetujui', 'ditolak', 'dibatalkan')),
  rejection_reason TEXT,
  processed_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Constraint EXCLUDE (Chapter 2 & AGENTS.md):
-- Mencegah dua reservasi berstatus 'disetujui' overlap pada fasilitas & tanggal yang sama.
-- HANYA berlaku untuk status = 'disetujui' (status 'menunggu' tetap boleh bertabrakan di antrean).
ALTER TABLE public.reservations
ADD CONSTRAINT no_overlapping_approved_reservations
EXCLUDE USING gist (
  facility_id WITH =,
  reservation_date WITH =,
  tsrange(
    (reservation_date + start_time),
    (reservation_date + end_time)
  ) WITH &&
) WHERE (status = 'disetujui');

-- Indexing
CREATE INDEX IF NOT EXISTS idx_reservations_facility_date 
  ON public.reservations(facility_id, reservation_date);
CREATE INDEX IF NOT EXISTS idx_reservations_facility_date_status
  ON public.reservations(facility_id, reservation_date, status);
CREATE INDEX IF NOT EXISTS idx_reservations_user_id 
  ON public.reservations(user_id);
CREATE INDEX IF NOT EXISTS idx_reservations_status_created 
  ON public.reservations(status, created_at);

-- Enable RLS on reservations
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- Helper function to get current user profile based on auth.uid()
CREATE OR REPLACE FUNCTION public.get_current_user_profile()
RETURNS TABLE (user_id BIGINT, role VARCHAR) AS $$
BEGIN
  RETURN QUERY
  SELECT u.id, u.role
  FROM public.users u
  WHERE u.auth_user_id = auth.uid()
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Enable RLS on users placeholder
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Users policies: pemilik profil hanya membaca dirinya sendiri;
-- petugas/admin dapat membaca profil lain untuk menampilkan nama pemohon
DROP POLICY IF EXISTS "Fivora users read own profile" ON public.users;
CREATE POLICY "Fivora users read own profile" ON public.users
  FOR SELECT USING (auth_user_id = auth.uid());

DROP POLICY IF EXISTS "Fivora staff can read all profiles" ON public.users;
CREATE POLICY "Fivora staff can read all profiles" ON public.users
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.get_current_user_profile() p
      WHERE p.role IN ('petugas', 'admin')
    )
  );

-- RLS Policies for reservations:
DROP POLICY IF EXISTS "Users can read own or approved reservations, staff can read all" ON public.reservations;
CREATE POLICY "Users can read own or approved reservations, staff can read all" ON public.reservations
  FOR SELECT USING (
    status = 'disetujui'
    OR user_id IN (SELECT user_id FROM public.get_current_user_profile())
    OR EXISTS (
      SELECT 1 FROM public.get_current_user_profile() p
      WHERE p.role IN ('petugas', 'admin')
    )
  );

DROP POLICY IF EXISTS "Users can insert own pending reservation" ON public.reservations;
CREATE POLICY "Users can insert own pending reservation" ON public.reservations
  FOR INSERT WITH CHECK (
    user_id IN (SELECT user_id FROM public.get_current_user_profile())
    AND status = 'menunggu'
  );

DROP POLICY IF EXISTS "Users can cancel own reservation, staff can update status" ON public.reservations;
CREATE POLICY "Users can cancel own reservation, staff can update status" ON public.reservations
  FOR UPDATE USING (
    user_id IN (SELECT user_id FROM public.get_current_user_profile())
    OR EXISTS (
      SELECT 1 FROM public.get_current_user_profile() p
      WHERE p.role = 'petugas'
    )
  )
  WITH CHECK (
    (
      user_id IN (SELECT user_id FROM public.get_current_user_profile())
      AND status = 'dibatalkan'
    )
    OR EXISTS (
      SELECT 1 FROM public.get_current_user_profile() p
      WHERE p.role = 'petugas'
    )
  );
