BEGIN;

-- Laporan dasar tidak ditutup ketika kegiatan perbaikannya masih terbuka.
CREATE OR REPLACE FUNCTION public.check_report_open_maintenance()
RETURNS TRIGGER
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  IF NEW.status IN ('selesai', 'ditolak') AND EXISTS (
    SELECT 1 FROM public.facility_maintenance AS m
    WHERE m.report_id = NEW.id AND m.completed_at IS NULL
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514',
      MESSAGE = 'Selesaikan perbaikan yang terkait dengan laporan ini sebelum menutup laporan.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reports_check_open_maintenance ON public.reports;
CREATE TRIGGER reports_check_open_maintenance
BEFORE UPDATE OF status ON public.reports
FOR EACH ROW EXECUTE FUNCTION public.check_report_open_maintenance();

-- Mengunci laporan yang sama dengan pembaruan status, termasuk saat insert
-- dilakukan melalui jalur lain. Laporan tertutup tidak diberi perbaikan terbuka.
CREATE OR REPLACE FUNCTION public.check_maintenance_report_open()
RETURNS TRIGGER
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = ''
AS $$
DECLARE v_status TEXT;
BEGIN
  IF NEW.completed_at IS NULL THEN
    SELECT r.status INTO v_status FROM public.reports AS r
    WHERE r.id = NEW.report_id FOR UPDATE;
    IF v_status IS DISTINCT FROM 'diproses' THEN
      RAISE EXCEPTION USING ERRCODE = '23514',
        MESSAGE = 'Perbaikan terbuka harus terkait dengan laporan berstatus Diproses.';
    END IF;
    -- Perubahan versi membuat form status lama gagal pada pemeriksaan CAS.
    -- Penulisan juga membuat perubahan serentak terdeteksi pada snapshot lama.
    UPDATE public.reports SET updated_at = clock_timestamp()
    WHERE id = NEW.report_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS maintenance_check_report_open ON public.facility_maintenance;
CREATE TRIGGER maintenance_check_report_open
BEFORE INSERT OR UPDATE OF report_id, facility_id, completed_at
ON public.facility_maintenance
FOR EACH ROW EXECUTE FUNCTION public.check_maintenance_report_open();

CREATE TABLE IF NOT EXISTS public.maintenance_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maintenance_id BIGINT NOT NULL REFERENCES public.facility_maintenance(id) ON DELETE RESTRICT,
  note TEXT NOT NULL CHECK (length(trim(note)) BETWEEN 1 AND 5000),
  created_by BIGINT NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  request_id UUID NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS maintenance_notes_history_idx
ON public.maintenance_notes (maintenance_id, created_at, id);

ALTER TABLE public.maintenance_notes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.maintenance_notes FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.maintenance_notes TO authenticated, service_role;
REVOKE ALL ON SEQUENCE public.maintenance_notes_id_seq FROM PUBLIC, anon, authenticated, service_role;

DROP POLICY IF EXISTS maintenance_notes_read_authorized ON public.maintenance_notes;
CREATE POLICY maintenance_notes_read_authorized
ON public.maintenance_notes FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users AS u
    WHERE u.auth_user_id = (SELECT auth.uid()) AND u.status = 'aktif'
    AND (
      u.role IN ('petugas', 'admin')
      OR (u.role = 'pengguna' AND EXISTS (
        SELECT 1 FROM public.facility_maintenance AS m
        JOIN public.reports AS r ON r.id = m.report_id
        WHERE m.id = maintenance_notes.maintenance_id AND r.user_id = u.id
      ))
    )
  )
);

CREATE OR REPLACE FUNCTION public.add_maintenance_note(
  p_maintenance_id BIGINT, p_note TEXT, p_request_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_staff_id BIGINT;
  v_maintenance public.facility_maintenance%ROWTYPE;
  v_existing public.maintenance_notes%ROWTYPE;
  v_note_id BIGINT;
BEGIN
  SELECT u.id INTO v_staff_id FROM public.users AS u
  WHERE u.auth_user_id = auth.uid() AND u.role = 'petugas' AND u.status = 'aktif'
  FOR SHARE;
  IF v_staff_id IS NULL THEN
    RAISE EXCEPTION 'Hanya petugas aktif yang dapat menambah catatan pemeriksaan.';
  END IF;
  IF p_note IS NULL OR length(trim(p_note)) NOT BETWEEN 1 AND 5000 THEN
    RAISE EXCEPTION 'Catatan pemeriksaan wajib diisi, maksimal 5000 karakter.';
  END IF;
  IF p_request_id IS NULL THEN
    RAISE EXCEPTION 'ID penyimpanan tidak valid. Muat ulang halaman.';
  END IF;

  SELECT m.* INTO v_maintenance FROM public.facility_maintenance AS m
  WHERE m.id = p_maintenance_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Perbaikan tidak ditemukan.'; END IF;

  -- Retry permintaan yang sudah tersimpan tidak membuat catatan ganda.
  SELECT n.* INTO v_existing FROM public.maintenance_notes AS n
  WHERE n.request_id = p_request_id;
  IF FOUND THEN
    IF v_existing.maintenance_id = p_maintenance_id
       AND v_existing.created_by = v_staff_id AND v_existing.note = trim(p_note) THEN
      RETURN jsonb_build_object('note_id', v_existing.id::TEXT);
    END IF;
    RAISE EXCEPTION 'ID penyimpanan sudah digunakan. Muat ulang data.';
  END IF;
  IF v_maintenance.completed_at IS NOT NULL THEN
    RAISE EXCEPTION 'Perbaikan sudah selesai. Catatan baru tidak dapat ditambahkan.';
  END IF;

  INSERT INTO public.maintenance_notes (maintenance_id, note, created_by, request_id)
  VALUES (p_maintenance_id, trim(p_note), v_staff_id, p_request_id)
  RETURNING id INTO v_note_id;
  RETURN jsonb_build_object('note_id', v_note_id::TEXT);
END;
$$;

REVOKE ALL ON FUNCTION public.check_report_open_maintenance() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.check_maintenance_report_open() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.add_maintenance_note(BIGINT, TEXT, UUID) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.add_maintenance_note(BIGINT, TEXT, UUID) TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
